name: Deploy static HTML to Azure Web App - ayan5

on:
  push:
    branches:
      - ayan
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_22382E3B59B944C7A85DA79D5007267D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E720DDAC077649B58039BA809859124F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6A2A9F14913C4E11A05CDED2119AAC0D }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ayan5'
          slot-name: 'Production'
          package: .
